apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: <namespace>
spec:
  selector:
    app: redis
  ports:
    - name: redis-cport
      port: 6379
      targetPort: 6379
  type: ClusterIP