apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: mongodb
  labels:
    app: mongodb
data:
  MONGO_INITDB_ROOT_USERNAME: "$(MONGO_INITDB_ROOT_USERNAME)"
  MONGO_INITDB_ROOT_PASSWORD: "$(MONGO_INITDB_ROOT_PASSWORD)"
  mongod.conf.orig: |
    storage:
      dbPath: /var/lib/mongodb
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
    net:
      port: 27017
      bindIp: 0.0.0.0  # Allow connections from any IP
    security:
      authorization: "enabled"  # Enable authentication
    replication:
      replSetName: rs0