apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
  labels:
    app: mongodb
data:
  mongodb-root-username: 'bW9uZ28tdXNlcg=='
  mongodb-root-password: 'SkppV3BPZFJwYzA3Ymw5'